// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // On indique explicitement à Node/tsx de charger le fichier .env
    seed: "npx tsx ./prisma/seed.ts", // Commande simplifiée et propre
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
